
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.digihealth.anesthesia.interfaceParameters.hnhtyy.lis.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-11-30T11:36:27.733+08:00
 * Generated source version: 3.1.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "InterfaceWebService",
                      portName = "InterfaceWebServiceSoap12",
                      targetNamespace = "WXLIS.Interface",
                      wsdlLocation = "http://192.168.0.124:81/default.asmx?wsdl",
                      endpointInterface = "interface.wxlis.InterfaceWebServiceSoap")
                      
public class InterfaceWebServiceSoap12Impl implements InterfaceWebServiceSoap {

    private static final Logger LOG = Logger.getLogger(InterfaceWebServiceSoap12Impl.class.getName());

    /* (non-Javadoc)
     * @see interface.wxlis.InterfaceWebServiceSoap#jybgxq(java.lang.String  xml )*
     */
    public java.lang.String jybgxq(java.lang.String xml) { 
        LOG.info("Executing operation jybgxq");
        System.out.println(xml);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see interface.wxlis.InterfaceWebServiceSoap#jybglb(java.lang.String  xml )*
     */
    public java.lang.String jybglb(java.lang.String xml) { 
        LOG.info("Executing operation jybglb");
        System.out.println(xml);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
