
package com.digihealth.anesthesia.interfaceParameters.hnhtyy.lis.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-11-30T11:36:27.720+08:00
 * Generated source version: 3.1.4
 * 
 */
public final class InterfaceWebServiceSoap_InterfaceWebServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("WXLIS.Interface", "InterfaceWebService");

    private InterfaceWebServiceSoap_InterfaceWebServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = InterfaceWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        InterfaceWebService ss = new InterfaceWebService(wsdlURL, SERVICE_NAME);
        InterfaceWebServiceSoap port = ss.getInterfaceWebServiceSoap();  
        
        {
        System.out.println("Invoking jybgxq...");
        java.lang.String _jybgxq_xml = "";
        java.lang.String _jybgxq__return = port.jybgxq(_jybgxq_xml);
        System.out.println("jybgxq.result=" + _jybgxq__return);


        }
        {
        System.out.println("Invoking jybglb...");
        java.lang.String _jybglb_xml = "";
        java.lang.String _jybglb__return = port.jybglb(_jybglb_xml);
        System.out.println("jybglb.result=" + _jybglb__return);


        }

        System.exit(0);
    }

}
