package com.digihealth.anesthesia.interfaceParameters.hnhtyy.lis.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.digihealth.anesthesia.interfaceParameters.hnhtyy.lis.form.ObjectFactory;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-11-30T11:36:27.756+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "WXLIS.Interface", name = "InterfaceWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface InterfaceWebServiceSoap {

    /**
     * 1.1.4.1.2.	检验报告详情查询
     */
    @WebResult(name = "jybgxqResult", targetNamespace = "WXLIS.Interface")
    @RequestWrapper(localName = "jybgxq", targetNamespace = "WXLIS.Interface", className = "_interface.wxlis.Jybgxq")
    @WebMethod(action = "WXLIS.Interface/jybgxq")
    @ResponseWrapper(localName = "jybgxqResponse", targetNamespace = "WXLIS.Interface", className = "_interface.wxlis.JybgxqResponse")
    public java.lang.String jybgxq(
        @WebParam(name = "xml", targetNamespace = "WXLIS.Interface")
        java.lang.String xml
    );

    /**
     * 1.1.4.1.1.1.    检验报告列表查询
     */
    @WebResult(name = "jybglbResult", targetNamespace = "WXLIS.Interface")
    @RequestWrapper(localName = "jybglb", targetNamespace = "WXLIS.Interface", className = "_interface.wxlis.Jybglb")
    @WebMethod(action = "WXLIS.Interface/jybglb")
    @ResponseWrapper(localName = "jybglbResponse", targetNamespace = "WXLIS.Interface", className = "_interface.wxlis.JybglbResponse")
    public java.lang.String jybglb(
        @WebParam(name = "xml", targetNamespace = "WXLIS.Interface")
        java.lang.String xml
    );
}
