package com.digihealth.anesthesia.interfaceParameters.hnhtyy.lis.service;


import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-11-30T11:36:27.770+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "InterfaceWebService", 
                  wsdlLocation = "http://192.168.0.124:81/default.asmx?wsdl",
                  targetNamespace = "WXLIS.Interface") 
public class InterfaceWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("WXLIS.Interface", "InterfaceWebService");
    public final static QName InterfaceWebServiceSoap12 = new QName("WXLIS.Interface", "InterfaceWebServiceSoap12");
    public final static QName InterfaceWebServiceSoap = new QName("WXLIS.Interface", "InterfaceWebServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.124:81/default.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InterfaceWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.124:81/default.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InterfaceWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InterfaceWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterfaceWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public InterfaceWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public InterfaceWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InterfaceWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns InterfaceWebServiceSoap
     */
    @WebEndpoint(name = "InterfaceWebServiceSoap12")
    public InterfaceWebServiceSoap getInterfaceWebServiceSoap12() {
        return super.getPort(InterfaceWebServiceSoap12, InterfaceWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterfaceWebServiceSoap
     */
    @WebEndpoint(name = "InterfaceWebServiceSoap12")
    public InterfaceWebServiceSoap getInterfaceWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(InterfaceWebServiceSoap12, InterfaceWebServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns InterfaceWebServiceSoap
     */
    @WebEndpoint(name = "InterfaceWebServiceSoap")
    public InterfaceWebServiceSoap getInterfaceWebServiceSoap() {
        return super.getPort(InterfaceWebServiceSoap, InterfaceWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterfaceWebServiceSoap
     */
    @WebEndpoint(name = "InterfaceWebServiceSoap")
    public InterfaceWebServiceSoap getInterfaceWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(InterfaceWebServiceSoap, InterfaceWebServiceSoap.class, features);
    }

}
