package com.digihealth.anesthesia.interfaceParameters.hnhtyy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-09-27T14:12:54.571+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "HBasicsWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HBasicsWebServiceSoap {

    /**
     * 服务总入口
     */
    @WebResult(name = "serviceResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @WebMethod(operationName = "BasicsService", action = "http://tempuri.org/service")
    public ServiceResponse basicsService(
        @WebParam(partName = "parameters", name = "service", targetNamespace = "http://tempuri.org/")
        Service parameters
    );
}
