package com.digihealth.anesthesia.interfaceParameters.hnhtyy;


import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-09-27T14:12:54.628+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "HBasicsWebService", 
                  wsdlLocation = "http://192.168.0.124:8087/HBasicsWebService.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
//@WebServiceClient(name = "HBasicsWebService", 
//wsdlLocation = "http://10.65.146.230:8087/HBasicsWebService.asmx?wsdl",
//targetNamespace = "http://tempuri.org/") 
public class HBasicsWebService extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "HBasicsWebService");
    public final static QName HBasicsWebServiceSoap12 = new QName("http://tempuri.org/", "HBasicsWebServiceSoap12");
    public final static QName HBasicsWebServiceSoap = new QName("http://tempuri.org/", "HBasicsWebServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.124:8087/HBasicsWebService.asmx?wsdl");
            //url = new URL("http://10.65.146.230:8087/HBasicsWebService.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HBasicsWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.124:8087/HBasicsWebService.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HBasicsWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HBasicsWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HBasicsWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HBasicsWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HBasicsWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HBasicsWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HBasicsWebServiceSoap
     */
    @WebEndpoint(name = "HBasicsWebServiceSoap12")
    public HBasicsWebServiceSoap getHBasicsWebServiceSoap12() {
        return super.getPort(HBasicsWebServiceSoap12, HBasicsWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HBasicsWebServiceSoap
     */
    @WebEndpoint(name = "HBasicsWebServiceSoap12")
    public HBasicsWebServiceSoap getHBasicsWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(HBasicsWebServiceSoap12, HBasicsWebServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns HBasicsWebServiceSoap
     */
    @WebEndpoint(name = "HBasicsWebServiceSoap")
    public HBasicsWebServiceSoap getHBasicsWebServiceSoap() {
        return super.getPort(HBasicsWebServiceSoap, HBasicsWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HBasicsWebServiceSoap
     */
    @WebEndpoint(name = "HBasicsWebServiceSoap")
    public HBasicsWebServiceSoap getHBasicsWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(HBasicsWebServiceSoap, HBasicsWebServiceSoap.class, features);
    }

}
